-- MySQL Script generated by MySQL Workbench
-- 04/28/15 14:47:08
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Locatie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Locatie` (
  `locatienr` INT NOT NULL,
  `straat` VARCHAR(50) NOT NULL,
  `huisnummer` VARCHAR(5) NOT NULL,
  `plaats` VARCHAR(25) NOT NULL,
  `postcode` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`locatienr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reis` (
  `reisID` INT NULL,
  `vertrektijd` DATETIME NOT NULL,
  `aankomsttijd` DATETIME NULL,
  `wekelijks` TINYINT(1) NULL,
  `beginLocatie` INT NOT NULL,
  `eindLocatie` INT NOT NULL,
  `routeID` INT NULL,
  `afstand` INT NULL,
  `koerier` INT NULL,
  PRIMARY KEY (`reisID`),
  INDEX `fk_Reis_Locatie1_idx` (`beginLocatie` ASC),
  INDEX `fk_Reis_Locatie2_idx` (`eindLocatie` ASC),
  CONSTRAINT `fk_Reis_Locatie1`
    FOREIGN KEY (`beginLocatie`)
    REFERENCES `mydb`.`Locatie` (`locatienr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reis_Locatie2`
    FOREIGN KEY (`eindLocatie`)
    REFERENCES `mydb`.`Locatie` (`locatienr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StakeholderType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StakeholderType` (
  `typeID` INT NOT NULL,
  `typenaam` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`typeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stakeholder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stakeholder` (
  `stakeholderID` INT NOT NULL,
  `type` INT NOT NULL,
  `naam` VARCHAR(30) NOT NULL,
  `achternaam` VARCHAR(30) NULL,
  `emailadres` VARCHAR(40) NOT NULL,
  `telefoonnr` VARCHAR(20) NOT NULL,
  `idkaart` VARCHAR(200) NULL,
  `ovkaart` VARCHAR(200) NULL,
  `krediet` DOUBLE NULL,
  `filiaalnummer` INT NULL,
  `wachtwoord` VARCHAR(50) NULL,
  `locatie` INT NULL,
  `snelheid` DOUBLE NULL,
  `rekeningnr` VARCHAR(20) NULL,
  PRIMARY KEY (`stakeholderID`),
  INDEX `fk_Stakeholder_Locatie1_idx` (`locatie` ASC),
  INDEX `fk_Stakeholder_StakeholderType1_idx` (`type` ASC),
  CONSTRAINT `fk_Stakeholder_Locatie1`
    FOREIGN KEY (`locatie`)
    REFERENCES `mydb`.`Locatie` (`locatienr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stakeholder_StakeholderType1`
    FOREIGN KEY (`type`)
    REFERENCES `mydb`.`StakeholderType` (`typeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VerzendOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VerzendOrder` (
  `orderID` INT NOT NULL,
  `klantID` INT NOT NULL,
  `aanmeldtijd` DATETIME NOT NULL,
  PRIMARY KEY (`orderID`),
  INDEX `fk_Order_Stakeholder1_idx` (`klantID` ASC),
  CONSTRAINT `fk_Order_Stakeholder1`
    FOREIGN KEY (`klantID`)
    REFERENCES `mydb`.`Stakeholder` (`stakeholderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Probleem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Probleem` (
  `probleemID` INT NULL,
  `beschrijving` VARCHAR(500) NOT NULL,
  `datum` DATETIME NOT NULL,
  `klantnr` INT NOT NULL,
  `titel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`probleemID`),
  INDEX `fk_Probleem_Stakeholder1_idx` (`klantnr` ASC),
  CONSTRAINT `fk_Probleem_Stakeholder1`
    FOREIGN KEY (`klantnr`)
    REFERENCES `mydb`.`Stakeholder` (`stakeholderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pakket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pakket` (
  `pakketnr` INT NOT NULL,
  `gewicht` DOUBLE NOT NULL,
  `formaat` VARCHAR(20) NOT NULL,
  `opmerking` VARCHAR(200) NULL,
  `probleemID` INT NOT NULL,
  `routeID` INT NOT NULL,
  `kosten` DOUBLE NOT NULL,
  `orderID` INT NOT NULL,
  PRIMARY KEY (`pakketnr`),
  INDEX `fk_Pakket_Reis1_idx` (`routeID` ASC),
  INDEX `fk_Pakket_Order1_idx` (`orderID` ASC),
  INDEX `fk_Pakket_Probleem1_idx` (`probleemID` ASC),
  CONSTRAINT `fk_Pakket_Reis1`
    FOREIGN KEY (`routeID`)
    REFERENCES `mydb`.`Reis` (`reisID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pakket_Order1`
    FOREIGN KEY (`orderID`)
    REFERENCES `mydb`.`VerzendOrder` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pakket_Probleem1`
    FOREIGN KEY (`probleemID`)
    REFERENCES `mydb`.`Probleem` (`probleemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bezorging`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bezorging` (
  `pakketnr` INT NOT NULL,
  `reisID` INT NOT NULL,
  `afhaaltijd` DATETIME NULL,
  `aflevertijd` DATETIME NULL,
  `probleemID` INT NULL,
  PRIMARY KEY (`pakketnr`, `reisID`),
  INDEX `fk_Bezorging_Reis1_idx` (`reisID` ASC),
  CONSTRAINT `fk_Bezorging_Reis1`
    FOREIGN KEY (`reisID`)
    REFERENCES `mydb`.`Reis` (`reisID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tarief`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tarief` (
  `koeriersID` INT NOT NULL,
  `km` INT NOT NULL,
  `prijs` DOUBLE NOT NULL,
  `extraPrijs` DOUBLE NOT NULL,
  PRIMARY KEY (`koeriersID`, `km`),
  CONSTRAINT `fk_Tarief_Stakeholder1`
    FOREIGN KEY (`koeriersID`)
    REFERENCES `mydb`.`Stakeholder` (`stakeholderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KredietOmzetting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`KredietOmzetting` (
  `treinkoerier` INT NOT NULL,
  `datum` DATETIME NOT NULL,
  `bedrag` DOUBLE NOT NULL,
  `isAfgehandeld` TINYINT(1) NULL,
  `type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`treinkoerier`, `datum`),
  CONSTRAINT `fk_KredietOmzetting_Stakeholder1`
    FOREIGN KEY (`treinkoerier`)
    REFERENCES `mydb`.`Stakeholder` (`stakeholderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
